### ISSUE TITLE
Memory Leak - Performance Issue on Android

### ISSUE THREAD

**Issue by WrathChaos** [venits/react-native-map-clustering#133] opened 2020-01-23 11:27 UTC
Hey @venits,
I'm using this library on our project and it has great memory leak issue on the Android side. It just ruins it. For now, I can use it with `clusteringEnabled={false}` prop and it works great without clustering. Can you take a look at this issue?

Thank you :)

**Comment by dikobrazik** [comment] 2020-01-27 09:44
Hi @WrathChaos 

If you are using this lib with custom markers, I suggest pass tracksViewChanges prop of Marker to false and redraw each marker, when it's needed, using .redraw() method. We had same problem and it was helped.

**Comment by WrathChaos** [comment] 2020-01-27 12:23
Hello @dikobrazik,
Thank you so much for the suggestion. We're using `tracksViewChanges` prop but it does not help with the Cluster. Can you share with me a basic example for the redraw suggestion?

**Comment by dikobrazik** [comment] 2020-01-31 10:45
@WrathChaos like this. And I was fork this repo and change some things according to RN Performance
<img width="580" alt="Снимок экрана 2020-01-31 в 13 41 19" src="https://user-images.githubusercontent.com/35029988/73533265-74af0400-442f-11ea-9841-ea8ad992e7ea.png">

**Comment by WrathChaos** [comment] 2020-01-31 12:06
@dikobrazik Got it! Thank you so much  :) I let this issue open because of the RN Performance would be implemented by default for this library.

**Comment by AFMW** [comment] 2020-02-07 19:19
Is there any way to improve the performance of it in android??

**Comment by BagasNS** [comment] 2020-02-21 18:59
is there any way to custom distance radius clustering?

**Comment by stephtea** [comment] 2020-02-21 21:30
I feel like custom markers is really common use case. Is there a path to getting a fix implemented?

**Comment by dikobrazik** [comment] 2020-02-22 04:50
> Is there any way to improve the performance of it in android??
> I'm showing the markers this way but its performance on android is really slow.
> Could it have any ways to be improved?
> PD: Attached a photo of my whole map/markers invocation.
> ![Screen Shot 2020-02-07 at 2 25 06 PM](https://user-images.githubusercontent.com/26683460/74059302-c585a600-49b5-11ea-9b58-f7fe7747dc7f.png)
In your case I can suggest separate MapView content, because as I see in your markers have depends from state and when you change state - your component will rerender.

**Comment by colloquet** [comment] 2020-03-14 08:40
I was having the same problem, I have found that the performance issues were caused by the ClusterMarkers. I ended up using the `renderCluster` prop to render my own ClusterMarkers, my own ClusterMarker is just the same as the default one except I have added `tracksViewChanges={false}` to the `Marker` component.

It's much better on Android after making this change , hope this helps.

**Comment by WrathChaos** [comment] 2020-03-14 12:21
@colloquet maybe you can open a PR for that?

**Comment by xseignard** [comment] 2020-04-17 06:18
@WrathChaos @colloquet I created a PR to handle that: https://github.com/venits/react-native-map-clustering/pull/150
Don't hesitate to comment if you see something wrong

**Comment by WrathChaos** [comment] 2020-04-17 10:59
@xseignard Hello, I've reviewed your PR :) Please check it out.

**Comment by venits** [comment] 2020-05-06 09:07
Fixed in module version `3.2.0`

Thank you for your contribution ❤️

**Comment by yurakruhlyk** [comment] 2020-05-12 16:50
I set tracksClusterViewChanges for MapView and tracksViewChanges for Marker, but still, have a problem on android(

**Comment by venits** [comment] 2020-05-13 18:06
Please look at this issue: https://github.com/venits/react-native-map-clustering/issues/161

I fixed it in version `3.3.6` :)

**Closed by venits** 2020-05-13 18:06 UTC
